#!/bin/sh

# alacritty scale factor
export WINIT_X11_SCALE_FACTOR=1

# load local variables
. "$XDG_CONFIG_HOME/X11/xinitrc.variables"

# load xresources
xrdb -load "$HOME/.config/X11/xresources"
xrdb -merge "$HOME/.config/X11/xresources.theme"

# disable pc speaker
xset -b

# pass DISPLAY variable to systemctl
if command -v systemctl &>/dev/null; then
  systemctl --user import-environment DISPLAY
fi

if [ -f "$XDG_CONFIG_HOME/X11/xinitrc.local" ]; then
  . "$XDG_CONFIG_HOME/X11/xinitrc.local"
fi

# start wm
mkdir -p "$HOME/.local/var/log/i3"
exec i3 >"$HOME/.local/var/log/i3/i3.log"
