import:
  move: no
  copy: no
  write: no

aunique:
  keys:
    - album
    - year
  bracket: "[]"

format_item: $album - $title
format_album: $album ($year)

sort_item: album+ disc+ track+
sort_album: album+

plugins:
  - edit
  - fetchart
  - info
  - mpdupdate
  - playlistc
  - scrub
  - smartplaylist

edit:
  itemfields:
    - album
    - albumartist
    - artist
    - composer
    - genre
    - grouping
    - title
    - track
    - year
  albumfields:
    - album
    - albumartist
    - year

fetchart:
  enforce_ratio: 0.5%
  cautious: yes
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
