import:
  move: false
  copy: false
  write: false

aunique:
  keys:
    - album
    - year
  bracket: "[]"

paths:
  default: '%lower{%dashify{%asciify{%romanize{$album}}}}/%lower{$track-%dashify{%asciify{%romanize{$title}}}}'
  singleton: '%lower{%dashify{%asciify{%romanize{$album}}}}/%lower{$track-%dashify{%asciify{%romanize{$title}}}}'
  comp: '%lower{%dashify{%asciify{%romanize{$album}}}}/%lower{$track-%dashify{%asciify{%romanize{$title}}}}'

replace:
  '[\\/]': '-'
  '^\.': '-'
  '[\x00-\x1f]': '-'
  '[<>:"\?\*\|]': '-'
  '\.$': ''
  '\s+$': ''
  '^\s+': ''
  '^-': ''
  '-$': ''

format_item: $album - $title
format_album: $album ($year)

sort_item: album+ disc+ track+
sort_album: album+

plugins:
  - edit
  - fetchart
  - info
  - mpdupdate
  - playlistc
  - romanize
  - scrub
  - smartplaylist
  - usertag
  - utilfuncs

edit:
  itemfields:
    - album
    - albumartist
    - artist
    - composer
    - genre
    - grouping
    - title
    - track
    - year
    - usertags
  albumfields:
    - album
    - albumartist
    - year

fetchart:
  enforce_ratio: 0.5%
  cautious: true
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
