#!/bin/bash

cd "$HOME" || exit

# Update submodules
echo "Initializing submodules"
yadm submodule update --recursive --init

# Initialize neovim with vim-plug
echo "Bootstrapping neovim"
nvim -c ":source stdpath('config')/init.vim" -c ":qall"

