#!/usr/bin/bash
if [ -z ${XDG_DATA_HOME} ]; then
  echo "Required environment variables unset -- re-login to load pam env"
  exit 1
fi

cd "$HOME" || exit

# Update submodules
echo "Initializing submodules..."
yadm submodule update --recursive --init

# Make file directories
echo "Creating file directories..."
files_dirs=(documents downloads games images lfs music programming share tmp)
mkdir -p "$HOME/files"
for dir in files_dirs; do
  mkdir "$HOME/files/$dir"
done

# Bootstrap neovim
nvim_bootstrap="$XDG_CONFIG_HOME/nvim/bootstrap"
if [ -f "$nvim_bootstrap" ]; then
  $nvim_bootstrap
fi
