local:
  beets:
    root_dir: ~/files/lfs/music
  class: tower
  distro: Arch
  hostname: origin
  i3:
    lock_command: lock-screen
    primary: HDMI-0
    secondary: HDMI-1
  net:
    interface: eno2
    type: ethernet
  os: Linux
  picom:
    flags: '-fCb -D8'
  user: '{{ .USER }}'
  xinit:
    default_brightness: 0.7
    xss_lock: false
