#!/bin/sh

# alacritty scale factor
export WINIT_X11_SCALE_FACTOR=1

# load local variables
. "$XDG_CONFIG_HOME/X11/xinitrc.variables"

# load xresources
xrdb -load "$HOME/.config/X11/xresources"
xrdb -merge "$HOME/.config/X11/xresources.theme"

# disable pc speaker
xset -b

# pass DISPLAY variable to systemctl
systemctl --user import-environment DISPLAY

# enable lockscreen if laptop
if [ "$class" == "laptop" ]; then
  xss-lock -- "$HOME/.local/bin/lock-screen" &
fi

# start compositor
mkdir -p "$HOME/.local/var/log/picom"
picom $PICOM_FLAGS >"$HOME/.local/var/log/picom/picom.log"

# start ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
mkdir -p "$HOME/.local/var/log/ibus"
ibus-daemon --xim &

# auto-adjust brightness
set-brightness $DEFAULT_BRIGHTNESS

# start wm
mkdir -p "$HOME/.local/var/log/i3"
exec i3 >"$HOME/.local/var/log/i3/i3.log"
