[bell]
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.padding]
x = 8
y = 8
