local font = 'JetBrains Mono Nerd Font'

local colors = {
    bright = {
        black = '#928374',
        blue = '#7daea3',
        cyan = '#89b482',
        green = '#a9b665',
        magenta = '#d3869b',
        red = '#ea6962',
        white = '#dfdf8e',
        yellow = '#e3a84e',
    },
    normal = {
        black = '#665c54',
        blue = '#7daea3',
        cyan = '#89b482',
        green = '#a9b665',
        magenta = '#d3869b',
        red = '#ea6962',
        white = '#dfdf8e',
        yellow = '#e78a4e',
    },
    primary = {
        background = '#282828',
        foreground = '#ebdbb2',
        alarm = '#ea6962',
    },
}

local M = {
    alacritty = { font = font, colors = colors, font_size = 10 },
    bat = { theme = 'gruvbox-dark' },
    dunst = {
        font = { family = font, size = 9 },
        colors = {
            low = {
                foreground = colors.primary.foreground,
                background = colors.primary.background,
            },
            normal = {
                foreground = colors.primary.foreground,
                background = colors.primary.background,
            },
            critical = {
                foreground = colors.primary.background,
                background = colors.primary.alarm,
            },
        },
    },
    eww = {
        font = font,
        colors = {
            background = colors.primary.background,
            foreground = colors.primary.foreground,
            black = colors.normal.black,
            blue = colors.bright.blue,
            red = colors.bright.red,
            yellow = colors.bright.yellow,
            darkyellow = colors.normal.yellow,
            green = colors.normal.green,
            widget = '#f2e5bc',
            hover = '#ebd696',
        },
    },
    fzf = { name = 'gruvbox-dark' },
    git = { delta = { theme = 'gruvbox' } },
    gtk = { theme = 'Gruvbox-Dark' },
    i3 = {
        font = { family = font, size = 10 },
        colors = {
            foc = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.bright.white,
            },
            foc_in = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            unfoc = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            urgent = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            ph = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
        },
        gaps = { inner = 5, outer = 0 },
    },
    igrep = { theme = 'dark' },
    nvim = { theme = 'gruvbox/dark' },
    rofi = { font = font, theme = 'gruvbox-dark' },
    zellij = {
        theme = 'gruvbox-dark',
        bg = colors.primary.background,
        bg1 = '#3c3836',
        fg = colors.primary.foreground,
        fg4 = '#a89984',
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
    },
    tmux = { theme = 'gruvbox-dark' },
    x11 = {
        colors = {
            background = colors.primary.background,
            foreground = colors.primary.foreground,
            c0 = colors.normal.black,
            c1 = colors.normal.red,
            c2 = colors.normal.green,
            c3 = colors.normal.yellow,
            c4 = colors.normal.blue,
            c5 = colors.normal.magenta,
            c6 = colors.normal.cyan,
            c7 = colors.normal.white,
            c8 = colors.bright.black,
            c9 = colors.bright.red,
            c10 = colors.bright.green,
            c11 = colors.bright.yellow,
            c12 = colors.bright.blue,
            c13 = colors.bright.magenta,
            c14 = colors.bright.cyan,
            c15 = colors.bright.white,
        },
    },
    wallpaper = { name = 'gruvbox-dark' },
    yazi = { colors = colors },
    zathura = { theme = 'gruvbox-dark' },
}

return M
