local font = 'JetBrains Mono Nerd Font'

local colors = {
    normal = {
        black = '#654735',
        red = '#c14a4a',
        green = '#6c782e',
        yellow = '#b47109',
        blue = '#45707a',
        magenta = '#945e80',
        cyan = '#4c7a5d',
        white = '#eee0b7',
    },
    bright = {
        black = '#654735',
        red = '#c14a4a',
        green = '#6c782e',
        yellow = '#b47109',
        blue = '#45707a',
        magenta = '#945e80',
        cyan = '#4c7a5d',
        white = '#eee0b7',
    },
    primary = {
        background = '#fbf1c7',
        foreground = '#282828',
        alarm = '#ea6962',
    },
    shades = {
        bg1 = '#ebdbb2',
        bg2 = '#ded0ab',
        bg3 = '#d5c4a1',
        bg4 = '#bdae93',
        fg4 = '#7c6f64',
    },
}

local M = {
    alacritty = { font = font, colors = colors, font_size = 10 },
    bat = { theme = 'gruvbox-light' },
    dunst = {
        font = { family = font, size = 9 },
        colors = {
            frame = colors.shades.bg2,
            low = {
                foreground = colors.primary.foreground,
                background = colors.primary.background,
            },
            normal = {
                foreground = colors.primary.foreground,
                background = colors.primary.background,
            },
            critical = {
                foreground = colors.primary.background,
                background = colors.primary.alarm,
            },
        },
    },
    eww = {
        font = font,
        colors = {
            background = colors.primary.background,
            foreground = colors.primary.foreground,
            black = colors.normal.black,
            blue = colors.bright.blue,
            red = colors.bright.red,
            yellow = colors.bright.yellow,
            darkyellow = colors.normal.yellow,
            green = colors.normal.green,
            widget = colors.shades.bg1,
            hover = colors.shades.bg2,
        },
    },
    fzf = { name = 'gruvbox-light' },
    git = { delta = { theme = 'gruvbox-light' } },
    gtk = { theme = 'Gruvbox-Light' },
    i3 = {
        font = { family = font, size = 10 },
        colors = {
            foc = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.bright.white,
            },
            foc_in = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            unfoc = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            urgent = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
            ph = {
                border = colors.primary.background,
                bg = colors.primary.background,
                text = colors.primary.foreground,
                indic = colors.primary.background,
                cborder = colors.primary.background,
            },
        },
        gaps = { inner = 5, outer = 0 },
    },
    igrep = { theme = 'light' },
    nvim = { theme = 'gruvbox/light' },
    rofi = { font = font, theme = 'gruvbox-light-soft' },
    zellij = {
        theme = 'gruvbox-light',
        bg = colors.primary.background,
        bg1 = colors.shades.bg1,
        fg = colors.primary.foreground,
        fg4 = colors.shades.fg4,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
    },
    tmux = { theme = 'gruvbox-light' },
    x11 = {
        colors = {
            background = colors.primary.background,
            foreground = colors.primary.foreground,
            c0 = colors.normal.black,
            c1 = colors.normal.red,
            c2 = colors.normal.green,
            c3 = colors.normal.yellow,
            c4 = colors.normal.blue,
            c5 = colors.normal.magenta,
            c6 = colors.normal.cyan,
            c7 = colors.normal.white,
            c8 = colors.bright.black,
            c9 = colors.bright.red,
            c10 = colors.bright.green,
            c11 = colors.bright.yellow,
            c12 = colors.bright.blue,
            c13 = colors.bright.magenta,
            c14 = colors.bright.cyan,
            c15 = colors.bright.white,
        },
    },
    wallpaper = { name = 'gruvbox-light' },
    yazi = { colors = colors },
    zathura = { theme = 'gruvbox-light' },
}

return M
