#!/bin/sh

eval "$(fasd --init auto)"
alias v='f -e nvim'

### REDEFINITIONS
alias ls="ls -a --color"
alias slack-term='slack-term -config "${XDG_CONFIG_HOME}/slack-term/config"'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias tmux='tmux -f ~/.config/tmux/tmux.conf'

### SHORTCUTS
alias x="exit"
alias la="ls -al --color"
alias rn="ranger"

##  misc
wtm() {
  echo "scale=2; $(wc -w $1 | awk '{print $1}') / 130" | bc
}

## git
gdiff() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview $preview
}

##  yadm
alias y="yadm"
alias yst="yadm status"
alias ya="yadm add"
alias yc="yadm commit"
alias ycmsg="yadm commit -m"
alias yp="yadm push"
alias yl="yadm pull"
alias yf="yadm fetch"
alias yd="yadm diff"

ydiff() {
  preview="yadm diff $@ --color=always -- {-1}"
  yadm diff $@ --name-only | fzf -m --ansi --preview $preview
}

##  neovim
rmnswap() {
  rm "$HOME/.local/share/nvim/swap/$(echo $1 | tr '/' '%').swp"
}

##  copy to clipboard
#   copy text
alias cclip="xclip -selection clipboard"
#   copy image
alias iclip="xclip -selection clipboard -t image/png -i"

##  dictd
#   wordnet english dictionary search
alias def="dict -d wn"
alias th="dict -d moby-thesaurus"

##  music
#   beet
alias beetup="beet update && beet splupdate"
alias beetrmd="beet rm -d"
#   mpd
alias mpcup="mpc update"
alias mpcdef="mpc clear && mpc random true && mpc repeat true && mpc load _japanese && mpc play"
#   youtube-dl
alias ydlmp3="youtube-dl --extract-audio --audio-format mp3"

##  mullvad
#   set relay location
alias mullvadsrl="mullvad relay set location"

##  pacman
#   browse packages
alias pacman-browse-pkgs="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
