#!/bin/sh

## User binaries
# Local user binaries
if [ -d "$HOME/.local/bin" ]; then
  export PATH="$PATH:$HOME/.local/bin"
fi

# Rust cargo installed binaries
_cargo_home=${CARGO_HOME:-$XDG_DATA_HOME/cargo}
if [ -d "$_cargo_home/bin" ]; then
  export PATH="$PATH:$_cargo_home/bin"
fi

# Yarn installed binaries
if [ -d "$HOME/.yarn/bin" ]; then
  export PATH="$PATH:$HOME/.yarn/bin";
fi

# Ruby gems installed binaries
if [ -d "$HOME/.gem/ruby/2.6.0/bin" ]; then
  export PATH="$PATH:$HOME/.gem/ruby/2.6.0/bin";
fi

# Go installed binaries
_go_home=${GOPATH:-$XDG_DATA_HOME/go}
if [ -d "$_go_home/bin" ]; then
  export PATH="$PATH:$_go_home/bin"
fi

## Java home directory
if [ -d "/usr/lib/jvm/java-11-jdk" ]; then
  export JAVA_HOME="/usr/lib/jvm/java-11-jdk";
  if [ -d "$JAVA_HOME/bin" ]; then
  export PATH="$PATH:$JAVA_HOME/bin"
  fi
fi

## TeXlive
# TeXlive binaries
if [ -d "/usr/local/share/texlive/2019/bin/x86_64-linux" ]; then
  export PATH="$PATH:/usr/local/share/texlive/2019/bin/x86_64-linux";
fi

# TeXlive man pages
if [ -d "/usr/local/share/texlive/2019/texmf-dist/doc/man" ]; then
  export MANPATH="$MANPATH:/usr/local/share/texlive/2019/texmf-dist/doc/man";
fi

# TeXlive info pages
if [ -d "/usr/local/share/texlive/2019/texmf-dist/doc/info" ]; then
  export INFOPATH="$INFOPATH:/usr/local/texlive/2019/texmf-dist/doc/info";
fi

## R user libraries directory
export R_PROFILE="$XDG_CONFIG_HOME/R/Rprofile"
export R_LIBS_USER="$XDG_DATA_HOME/R/library"
