#!/bin/sh
eval "$(fasd --init auto)"
alias v="f -e $EDITOR"

### REDEFINITIONS
alias ls="ls -a --color"

### SHORTCUTS
alias x="exit"
alias la="ls -al --color"
alias rn="ranger"

##  misc
wtm() {
  echo "scale=2; $(wc -w $1 | awk '{print $1}') / 130" | bc
}
