#!/bin/sh

# Local user binaries
if [ -d "$HOME/.local/bin" ]; then
  export PATH="$PATH:$HOME/.local/bin"
fi

# Rust cargo installed binaries
_cargo_home=${CARGO_HOME:-$XDG_DATA_HOME/cargo}
if [ -d "$_cargo_home/bin" ]; then
  export PATH="$PATH:$_cargo_home/bin"
fi

# Yarn installed binaries
if [ -d "$HOME/.local/share/npm/bin" ]; then
  export PATH="$PATH:$HOME/.local/share/npm/bin"
fi

# Ruby gems installed binaries
if [ -d "$HOME/.local/share/gem/bin" ]; then
  export PATH="$PATH:$HOME/.local/share/gem/bin"
fi

# Go installed binaries
_go_home=${GOPATH:-$XDG_DATA_HOME/go}
if [ -d "$_go_home/bin" ]; then
  export PATH="$PATH:$_go_home/bin"
fi

# ghcup installed tool binaries
if [ -d "$GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin" ]; then
  export PATH="$PATH:$GHCUP_INSTALL_BASE_PREFIX/.ghcup/bin"
fi
