---
yarnPath: .local/share/node/corepack/yarn/3.1.1/yarn.js
globalFolder: .local/share/yarn/global
deferredVersionFolder: .local/share/yarn/versions
cacheFolder: .cache/yarn/cache
pnpUnpluggedFolder: .cache/yarn/unplugged
virtualFolder: .cache/yarn/__virtual__
installStatePath: .cache/yarn/install-state.gz
